.TH SENSOR-HRLV 1
.SH NAME
sensor-hrlv \- read HRLV sensors attached to a WildlifeSystems node
.SH SYNOPSIS
.B sensor-hrlv
.SH DESCRIPTION
.B sensor-hrlv
Reads temperature and humidity data from a HRLV sensor attached to the Raspberry Pi.
.SH OPTIONS
.TP
None
.SH NOTES
This program is designed to be used with the \fBsr\fR program (sensor-read) from WildlifeSystems.
